### ISSUE TITLE
Thanks for Sharing the Code

### ISSUE THREAD

**Issue by PodeCaradox** [trgrote/JPS-Unity#2]
I implemented your Code in my game and changed a little bit of it and it just work great :)

![grafik](https://user-images.githubusercontent.com/5760157/75975829-87f33a80-5ed9-11ea-981a-4756f72031a1.png)

![grafik](https://user-images.githubusercontent.com/5760157/75975873-980b1a00-5ed9-11ea-87d8-6d88efe9b90e.png)

**Comment by trgrote** [comment]
Awesome.  Glad it worked!
